In [6]:
import numpy as np

# States
states=["CP", "IP"]

# Observation sequence
obs_sequence=["lem","icet","cola"]

N=len(states)
T=len(obs_sequence)+1

# Transition matrix
trans_prob=[
    [0.7,0.3] ,  
    [0.5,0.5]  
]

# Emission probabilities
emit_prob={
    "CP":{"lem":0.3,"icet":0.1,"cola":0.6},
    "IP":{"lem":0.2,"icet":0.7,"cola":0.1}
}

# Alpha matrix
alpha = np.zeros((N, T))

# Initialization
alpha[0][0]=1
alpha[1][0]=0

print("Initial Alpha Matrix")
print(alpha)

# Forward algorithm
for t in range(1,T):

    for i in range(N):

        total=0

        for j in range(N):

            prev=alpha[j][t - 1]

            transition=trans_prob[j][i]

            emission=emit_prob[states[j]][obs_sequence[t - 1]]

            total=total + prev * transition * emission

        alpha[i][t]=total

    print("\nAlpha values at time step", t)
    print(alpha)

# Final probability
final_prob = 0

for i in range(N):
    final_prob = final_prob + alpha[i][T - 1]

print("\nFinal Probability =", final_prob)

print("\nFinal Alpha Matrix")
print(alpha)

Initial Alpha Matrix
[[1. 0. 0. 0.]
 [0. 0. 0. 0.]]

Alpha values at time step 1
[[1.   0.21 0.   0.  ]
 [0.   0.09 0.   0.  ]]

Alpha values at time step 2
[[1.     0.21   0.0462 0.    ]
 [0.     0.09   0.0378 0.    ]]

Alpha values at time step 3
[[1.       0.21     0.0462   0.021294]
 [0.       0.09     0.0378   0.010206]]

Final Probability = 0.03149999999999999

Final Alpha Matrix
[[1.       0.21     0.0462   0.021294]
 [0.       0.09     0.0378   0.010206]]


In [2]:
# BACKWARD ALGORITHM
import numpy as np

# States
states = ["CP", "IP"]

# Observation sequence
obs_sequence = ["lem", "icet", "cola"]

N = len(states)
T = len(obs_sequence) + 1

# Transition matrix
trans_prob = [
    [0.7, 0.3],
    [0.5, 0.5]
]

# Emission probabilities
emit_prob = {
    "CP": {"lem": 0.3, "icet": 0.1, "cola": 0.6},
    "IP": {"lem": 0.2, "icet": 0.7, "cola": 0.1}
}

# Beta matrix
beta = np.zeros((N, T))

# Initialization
for i in range(N):
    beta[i][T - 1] = 1

print("\nInitial Beta Matrix")
print(beta)

# Backward algorithm
for t in range(T - 2, -1, -1):

    for i in range(N):

        total = 0

        for j in range(N):

            transition = trans_prob[i][j]

            emission = emit_prob[states[j]][obs_sequence[t]]

            next_beta = beta[j][t + 1]

            total = total + transition * emission * next_beta

        beta[i][t] = total

    print("\nBeta values at time step", t)
    print(beta)

# Final probability
final_prob = 0

for i in range(N):
    final_prob = final_prob + beta[i][0]

print("\nFinal Probability =", final_prob)

print("\nFinal Beta Matrix")
print(beta)


Initial Beta Matrix
[[0. 0. 0. 1.]
 [0. 0. 0. 1.]]

Beta values at time step 2
[[0.   0.   0.45 1.  ]
 [0.   0.   0.35 1.  ]]

Beta values at time step 1
[[0.    0.105 0.45  1.   ]
 [0.    0.145 0.35  1.   ]]

Beta values at time step 0
[[0.03075 0.105   0.45    1.     ]
 [0.03025 0.145   0.35    1.     ]]

Final Probability = 0.06099999999999999

Final Beta Matrix
[[0.03075 0.105   0.45    1.     ]
 [0.03025 0.145   0.35    1.     ]]
